### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by tomarney**
I wrote a guide to myself for importing TACtool CSV files into ESI laser software, and I've finally got round to tidying it up and submitting it as a PR. I hope it's useful!

While I was adding to the docs, I also took the opportunity to make them a bit more user-friendly by making it clearer that the "Installation" section is only if you know what you're doing - that most people will just want to download the latest release. I also moved the guides to the standard docs folder, and added a screenshot to the main README to show off the app!

I hope you find the suggestions useful.

### CODE REVIEW

**Comment by leorudczenko** [comment]
Hi Tom, thank you for taking the time to write this and submit it as a pull request. It looks very useful and includes good amount of detail for those who may lack the technical experience.

I believe this is the same software we use within BGS, and so I can see this being a valuable addition to the documentation. I'll double check that this is the same software before taking this pull request further.

**Comment by tomarney** [comment]
Hi Leo, thanks for considering my PR!

If TACtool is intended for wider community use, wouldn't the import guide be useful to have in the docs even if it's not relevant for the BGS specifically? If it's also the software BGS uses, then that's even better.

**Review by leorudczenko — APPROVED** [review]

**Comment by leorudczenko** [comment]
Yes that is a good point Tom. I've just reviewed your documents and made a small tweak, but we are going to accept this contribution to TACtool! Thank you very much for your efforts in improving the software for other users, it's greatly appreciated 🙂

**Comment by volcan01010** [comment]
Thanks @tomarney - it's really satisfying to know that there are other people out there using our code and even better that they care enough to make it better.

**Pull request merged**
